seed_everything: 42

data:
  class_path: src.gm_dataset.GMDataModule
  init_args:
    cfg_path: src/GraphMatching/experiments/spair.json
    num_keypoints: 7
    eval_samples: 256
    eval_on_test: False
    train_eval_samples: 128 
    eval_batch_size: 64
    num_workers:  4
    train_batch_size: 8
    train_epoch_iters: 400
    test_samples: -1

model:
  class_path: src.models.GMModel
  init_args:
    core:
      class_path: src.cores.SolverFreeCore
      init_args:
        encoder:
          class_path: src.CombOptNet.src.encoders.DisjointEncoder
          init_args:
            ab_encoders:
              - class_path: src.CombOptNet.src.encoders.StaticABEncoder
                init_args:
                  num_vars: 49
                  num_constrs: 14
                  batch_size_extractor: src.GraphMatching.utils.utils.get_batch_size
                  init_a:
                    class_path: torch.nn.init.uniform_
                    init_args:
                      a: -0.5
                      b: 0.5
                  init_r:
                    class_path: torch.nn.init.constant_
                    init_args:
                      val: 0.2
                  init_o:
                    class_path: torch.nn.init.uniform_
                    init_args:
                      a: 0.25
                      b: 0.75

            c_encoder:
              class_path: src.encoders.KeyPointMatchingCEncoder
              init_args:
                pretrained_path: runs/neurips/kpcamera/ilploss1030_NS4H_init/val-256/seed-42/kp4/version_0/checkpoints/best.ckpt
                prefix: 'core.encoder.c_encoder.net.' 
                backbone_params:
                  alpha: 0.0
        
        known_ab_encoder: 
          class_path: src.encoders.LUToABEncoder
          init_args:
            lu_encoder: 
              class_path: src.encoders.StaticLUEncoder
              init_args:
                batch_size_extractor: src.GraphMatching.utils.utils.get_batch_size
                num_vars: 49
                lb: -0.485
                ub: 1.485 
                #              class_path: src.CombOptNet.src.encoders.StaticABEncoder
                #              init_args:
                #                num_vars: 10
                #                num_constrs: 20

        sampler:
          class_path: src.samplers.SamplerList
          init_args:
            samplers:
              - class_path: src.samplers.BatchSampler
              - class_path: src.samplers.BitNbrSampler
              - class_path: src.samplers.RandIntNbrWrapper
                init_args:
                  sampler:
                    class_path: src.samplers.ProjSampler

              - class_path: src.samplers.BitKHopSampler
                init_args:
                  num_hops: 2
                  num_samples: 49

              - class_path: src.samplers.BitKHopSampler
                init_args:
                  num_hops: 3
                  num_samples: 49 

              - class_path: src.samplers.BitKHopSampler
                init_args:
                  num_hops: 4
                  num_samples: 49



            

        criterion:
          class_path: src.losses.ILPLoss
          init_args:
            pos_param: 0.01
            neg_param: 0.01
            criterion: hinge
            balancer:
              class_path: src.losses.CoVBalancer
              init_args:
                num_losses: 3

    solver:
      class_path: src.CombOptNet.src.ilp.CombOptNet
      init_args:
        vtype: 'B'
        env:
          class_path: gurobi.Env
          init_args:
            params:
              OutputFlag: 0
              TimeLimit: 10
        num_workers: 10

    optimizer:
      custom:
        '.*node_layers.*':
            lr: 2.5e-5
        '.*edge_layers.*':
            lr: 2.5e-5
        '.*final_layers.*':
            lr: 2.5e-5

      class_path: torch.optim.AdamW
      init_args:
        lr: 1.0e-3
        weight_decay: 0.0

    lr_scheduler:
      class_path: torch.optim.lr_scheduler.MultiStepLR
      init_args:
         gamma: 0.1
         milestones: [1000] 

    schedulers:
      "temp":
        class_path: torch.optim.lr_scheduler.MultiStepLR
        init_args:
          gamma: 0.2
          milestones: [10,30]
        init: 0.5


skip_initial_validation: 1
trainer:
  max_epochs: 100
  min_epochs: 35
  callbacks:
    - class_path: src.callbacks.Timer
    - class_path: src.callbacks.CustomLogging
    - class_path: pytorch_lightning.callbacks.Timer
      init_args:
        duration: 01:00:00:00
        interval: step

    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        monitor: val/acc/num
        patience: 10
        mode: max
    - class_path: pytorch_lightning.callbacks.ModelSummary
      init_args:
        max_depth: -1
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step

    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        monitor: 'val/acc/num'
        mode: 'max'
        filename: best
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        save_on_train_epoch_end: True  
        save_last: True

 
  log_every_n_steps: 10
  check_val_every_n_epoch: 1
  logger:
    class_path: pytorch_lightning.loggers.TensorBoardLogger
    init_args:
      save_dir: runs/neurips/kpcamera/ilploss1030_NS4H_init/val-256/seed-42
      name: kp7
      default_hp_metric: false
  gpus: 1
  num_sanity_val_steps: 0
  reload_dataloaders_every_n_epochs: 0
